### ISSUE TITLE
results seem to cache unexpectedly

### ISSUE THREAD

**Issue by dgarbartopti** [jtmoon79/super-speedy-syslog-searcher#273]
### Describe the bug

When repeatedly invoking the CLI on the same root directory, the resulting queries cache the results even when the underlying data sources are changed out.

### To Reproduce

1.  The Commands

Install two AWS EBS BundleLogs directories into a folder such as `sample-data/BundleLogs-$timestamp`. The timestamps are different for both directories.

```
user@host:~/Downloads/sample-data$ s4 . -a 20240402 -b @+1d
```

The date the command was run was on 2024-04-02 as one would imagine, a roundabout way of getting "today".

At some point, delete the folders inside `sample-data` and replace them with a different set of data (two new `BundleLogs-$timestamp` folders, with two new completely different timestamps).

```
user@host:~/Downloads/sample-data$ s4 . -a 20240404 -b @+1d
```

This command produces no output, until the `-a` date is modified to be within range of one of the first times s4 was invoked within that directory.

2. What are the log files used? Either attach a .zip or provide an inline sample that reproduces the Issue.

Unzipped AWS EBS log file bundles. There is too much data to anonymize at the moment.

3a. What did you expect to occur?

The data show me the most up to date analysis of the directory in question.

3b. What actually occurred?

The data was cutting off at 2024-04-02 even though it had been replaced with files that included data all the way up until 2024-04-05.

### Environment:

 - OS: Pop!_OS 22.04 LTS 64-bit
 - s4 version: super_speedy_syslog_searcher 0.6.70
 - terminal: GNOME Terminal (Version 3.44.0 for GNOME 42)
 - bash: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Screenshots

It wasn't until I renamed the directories that I confirmed it was an issue with the PWD of the execution, and it'd take another day before I get a more clear-cut example from my own logs, so I won't have anything so brief to illustrate the effect

### Additional context

Maybe it has something to do with the data being a super-set of each-other, but because the directories between `sample-data` and the actual log files had completely new names, I would expect them to not be cached.

It's entirely possible something between my terminal and s4 is responsible for the caching but that would be the first I'd ever heard of something like that being installed or enabled by default on a distro.

I appreciate the tool, it's surprising that there's so few things that work for cases like this.

**Comment by jtmoon79** [comment]
Thanks for the report @dgarbartopti 

Is it possible to attach a zip of the files with only the first 5 lines and last 5 lines? (obviously, overwrite any PII with random whatever)

**Comment by jtmoon79** [comment]
Thanks for the report @dgarbartopti 

Is it possible to attach a zip of the files with only the first 5 lines and last 5 lines of each file? (obviously, overwrite any PII with random whatever)

**Comment by jtmoon79** [comment]
> the resulting queries cache the results even when the underlying data sources are changed out.

@dgarbartopti I'm very sure this is not a caching between runs of `s4` as that is not something I implemented.
The most likely possibility of caching occurring is because `$PWD` is some kind of highly cached network storage.  But I don't think that's it.

One possibility is the files have log messages with datetimestamps not in chronological order.

But my gut feeling is you might be just mixing things up.  Are _really certain_ these files have the datetimestamps you think they do?  You wouldn't be the first to make such a PBKAC error (I've had many such errors that made it into bug reports 😊)

Something to check: try running with options `-uwp`. This will help you track down where each log messages is taken and what UTC datetime `s4` believes the log message is.  This has helped me navigate some confusing runs of `s4`.

> Unzipped AWS EBS log file bundles. There is too much data to anonymize at the moment.

But also, if you can get me a zip with the samples of the log, per my prior comment above, that would help me the most.  If there are too many, then a small subset with which you observed the problem.

**Comment by jtmoon79** [comment]
Closed Issue. Not enough information.
